# ASP.NET Core


# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*
- feature-*
- nginx

pool:
  #vmImage: 'ubuntu-latest'
  name: 'SelfHostedPcAlberto'

variables:
  buildConfiguration: 'Release'
  imageName: 'acolom83/pipelines-dotnet-core-dockerhub'
  dockerHubCoonectionName: 'Acolom83_DokerHub_ServiceConnectionName'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

#https://docs.microsoft.com/es-es/azure/devops/pipelines/tasks/build/docker?view=azure-devops
steps:
#login en docker
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(dockerHubCoonectionName)
#publicar el contenidor con la etiqueta del build id
- task: Docker@2
  displayName: Build and push
  inputs:
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: $(Build.BuildId)
    containerRegistry: |
      $(dockerHubCoonectionName)
    repository: $(imageName)
#copiar el fichero docker-compose-azure.yml a la salida
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/docker-compose-azure.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
#reemplazar los tokens basicamente se trata de modificar el docker-compose-azure.yml para que contenga la etiqueta $(Build.BuildId)
- task: replacetokens@3
  inputs:
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    targetFiles: '**/docker-compose-azure.yml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '$('
    tokenSuffix: ')'
    useLegacyPattern: false
    enableTelemetry: true
# publicar el artefacto para que luego el release lo pueda recuperar
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'docker-compose-azure.yml'
    publishLocation: 'Container'

